-- vim.keymap.set("n", "<space>cc", function ()
--   require("sg.cody.commands").toggle()
-- end)
--
-- vim.keymap.set("v", "<space>a", ":CodyContext<CR>")
-- vim.keymap.set("v", "<space>e", ":CodyExplain<CR>")
